=== hogenesch/circadb2/data_build/schemas/gene.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "CircaDB Gene",
  "type": "object",
  "required": [
    "id",
    "symbol",
    "name",
    "aliases",
    "species",
    "external_ids",
    "available_datasets"
  ],
  "properties": {
    "id": {
      "type": "string"
    },
    "symbol": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "aliases": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "species": {
      "type": "string"
    },
    "external_ids": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "available_datasets": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "id",
          "slug",
          "title",
          "profile_path"
        ],
        "properties": {
          "id": {
            "type": "string"
          },
          "slug": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "profile_path": {
            "type": "string"
          }
        }
      }
    }
  }
}

=== hogenesch/circadb2/public_data/genes/NLGN3.json
{
  "id": "mmu:nlgn3",
  "symbol": "Nlgn3",
  "name": "Nlgn3",
  "aliases": [
    "2900075N08Rik"
  ],
  "species": "Mus musculus",
  "external_ids": {},
  "available_datasets": [
    {
      "id": "hughes-2009",
      "slug": "hughes-2009",
      "title": "Hughes et al. 2009 Mouse Liver 48h",
      "profile_path": "/public_data/profiles/hughes-2009/NLGN3.json"
    }
  ]
}

=== hogenesch/circadb2/site/public/public_data/genes/NAT8F1.json
{
  "id": "mmu:nat8f1",
  "symbol": "Nat8f1",
  "name": "Nat8f1",
  "aliases": [],
  "species": "Mus musculus",
  "external_ids": {},
  "available_datasets": [
    {
      "id": "hughes-2009",
      "slug": "hughes-2009",
      "title": "Hughes et al. 2009 Mouse Liver 48h",
      "profile_path": "/public_data/profiles/hughes-2009/NAT8F1.json"
    }
  ]
}

=== hogenesch/circadb2/site/public/public_data/genes/IRAK4.json
{
  "id": "mmu:irak4",
  "symbol": "Irak4",
  "name": "Irak4",
  "aliases": [],
  "species": "Mus musculus",
  "external_ids": {},
  "available_datasets": [
    {
      "id": "hughes-2009",
      "slug": "hughes-2009",
      "title": "Hughes et al. 2009 Mouse Liver 48h",
      "profile_path": "/public_data/profiles/hughes-2009/IRAK4.json"
    }
  ]
}

=== hogenesch/circadb2/public_data/genes/LOC102642336.json
{
  "id": "mmu:loc102642336",
  "symbol": "LOC102642336",
  "name": "LOC102642336",
  "aliases": [
    "Ttc6"
  ],
  "species": "Mus musculus",
  "external_ids": {},
  "available_datasets": [
    {
      "id": "hughes-2009",
      "slug": "hughes-2009",
      "title": "Hughes et al. 2009 Mouse Liver 48h",
      "profile_path": "/public_data/profiles/hughes-2009/LOC102642336.json"
    }
  ]
}

=== hogenesch/circadb2/site/public/public_data/genes/AP1M1.json
{
  "id": "mmu:ap1m1",
  "symbol": "Ap1m1",
  "name": "Ap1m1",
  "aliases": [],
  "species": "Mus musculus",
  "external_ids": {},
  "available_datasets": [
    {
      "id": "hughes-2009",
      "slug": "hughes-2009",
      "title": "Hughes et al. 2009 Mouse Liver 48h",
      "profile_path": "/public_data/profiles/hughes-2009/AP1M1.json"
    }
  ]
}

=== hogenesch/circadb2/public_data/genes/CREB3L2.json
{
  "id": "mmu:creb3l2",
  "symbol": "Creb3l2",
  "name": "Creb3l2",
  "aliases": [],
  "species": "Mus musculus",
  "external_ids": {},
  "available_datasets": [
    {
      "id": "hughes-2009",
      "slug": "hughes-2009",
      "title": "Hughes et al. 2009 Mouse Liver 48h",
      "profile_path": "/public_data/profiles/hughes-2009/CREB3L2.json"
    }
  ]
}

=== hogenesch/circadb2/site/public/public_data/genes/HERC4.json
{
  "id": "mmu:herc4",
  "symbol": "Herc4",
  "name": "Herc4",
  "aliases": [],
  "species": "Mus musculus",
  "external_ids": {},
  "available_datasets": [
    {
      "id": "hughes-2009",
      "slug": "hughes-2009",
      "title": "Hughes et al. 2009 Mouse Liver 48h",
      "profile_path": "/public_data/profiles/hughes-2009/HERC4.json"
    }
  ]
}

=== hogenesch/circadb2/site/public/public_data/genes/GAA.json
{
  "id": "mmu:gaa",
  "symbol": "Gaa",
  "name": "Gaa",
  "aliases": [],
  "species": "Mus musculus",
  "external_ids": {},
  "available_datasets": [
    {
      "id": "hughes-2009",
      "slug": "hughes-2009",
      "title": "Hughes et al. 2009 Mouse Liver 48h",
      "profile_path": "/public_data/profiles/hughes-2009/GAA.json"
    }
  ]
}
