=== hogenesch/circadb2/data_build/schemas/gene.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "CircaDB Gene",
  "type": "object",
  "required": [
    "id",
    "symbol",
    "name",
    "aliases",
    "species",
    "external_ids",
    "available_datasets"
  ],
  "properties": {
    "id": {
      "type": "string"
    },
    "symbol": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "aliases": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "species": {
      "type": "string"
    },
    "external_ids": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "available_datasets": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "id",
          "slug",
          "title",
          "profile_path"
        ],
        "properties": {
          "id": {
            "type": "string"
          },
          "slug": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "profile_path": {
            "type": "string"
          }
        }
      }
    }
  }
}

=== hogenesch/circadb2/site/public/public_data/genes/GM31474.json
{
  "id": "mmu:gm31474",
  "symbol": "Gm31474",
  "name": "Gm31474",
  "aliases": [],
  "species": "Mus musculus",
  "external_ids": {},
  "available_datasets": [
    {
      "id": "hughes-2009",
      "slug": "hughes-2009",
      "title": "Hughes et al. 2009 Mouse Liver 48h",
      "profile_path": "/public_data/profiles/hughes-2009/GM31474.json"
    }
  ]
}

=== hogenesch/circadb2/public_data/genes/EXOSC10.json
{
  "id": "mmu:exosc10",
  "symbol": "Exosc10",
  "name": "Exosc10",
  "aliases": [],
  "species": "Mus musculus",
  "external_ids": {},
  "available_datasets": [
    {
      "id": "hughes-2009",
      "slug": "hughes-2009",
      "title": "Hughes et al. 2009 Mouse Liver 48h",
      "profile_path": "/public_data/profiles/hughes-2009/EXOSC10.json"
    }
  ]
}

=== hogenesch/circadb2/site/public/public_data/genes/2210019G11RIK.json
{
  "id": "mmu:2210019g11rik",
  "symbol": "2210019G11Rik",
  "name": "2210019G11Rik",
  "aliases": [],
  "species": "Mus musculus",
  "external_ids": {},
  "available_datasets": [
    {
      "id": "hughes-2009",
      "slug": "hughes-2009",
      "title": "Hughes et al. 2009 Mouse Liver 48h",
      "profile_path": "/public_data/profiles/hughes-2009/2210019G11RIK.json"
    }
  ]
}

=== hogenesch/circadb2/site/public/public_data/genes/GPR137B-PS.json
{
  "id": "mmu:gpr137b-ps",
  "symbol": "Gpr137b-ps",
  "name": "Gpr137b-ps",
  "aliases": [],
  "species": "Mus musculus",
  "external_ids": {},
  "available_datasets": [
    {
      "id": "hughes-2009",
      "slug": "hughes-2009",
      "title": "Hughes et al. 2009 Mouse Liver 48h",
      "profile_path": "/public_data/profiles/hughes-2009/GPR137B-PS.json"
    }
  ]
}

=== hogenesch/circadb2/public_data/genes/C030034I22RIK.json
{
  "id": "mmu:c030034i22rik",
  "symbol": "C030034I22Rik",
  "name": "C030034I22Rik",
  "aliases": [],
  "species": "Mus musculus",
  "external_ids": {},
  "available_datasets": [
    {
      "id": "hughes-2009",
      "slug": "hughes-2009",
      "title": "Hughes et al. 2009 Mouse Liver 48h",
      "profile_path": "/public_data/profiles/hughes-2009/C030034I22RIK.json"
    }
  ]
}

=== hogenesch/circadb2/public_data/genes/PIFO.json
{
  "id": "mmu:pifo",
  "symbol": "Pifo",
  "name": "Pifo",
  "aliases": [],
  "species": "Mus musculus",
  "external_ids": {},
  "available_datasets": [
    {
      "id": "hughes-2009",
      "slug": "hughes-2009",
      "title": "Hughes et al. 2009 Mouse Liver 48h",
      "profile_path": "/public_data/profiles/hughes-2009/PIFO.json"
    }
  ]
}

=== hogenesch/circadb2/site/public/public_data/genes/CCDC103.json
{
  "id": "mmu:ccdc103",
  "symbol": "Ccdc103",
  "name": "Ccdc103",
  "aliases": [],
  "species": "Mus musculus",
  "external_ids": {},
  "available_datasets": [
    {
      "id": "hughes-2009",
      "slug": "hughes-2009",
      "title": "Hughes et al. 2009 Mouse Liver 48h",
      "profile_path": "/public_data/profiles/hughes-2009/CCDC103.json"
    }
  ]
}

=== hogenesch/circadb2/site/public/public_data/genes/KLK1B27.json
{
  "id": "mmu:klk1b27",
  "symbol": "Klk1b27",
  "name": "Klk1b27",
  "aliases": [],
  "species": "Mus musculus",
  "external_ids": {},
  "available_datasets": [
    {
      "id": "hughes-2009",
      "slug": "hughes-2009",
      "title": "Hughes et al. 2009 Mouse Liver 48h",
      "profile_path": "/public_data/profiles/hughes-2009/KLK1B27.json"
    }
  ]
}
